version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: "redis:6.2.6"
    volumes:
      - "./tmp/redis:/data"
